# Generated by Django 3.1.5 on 2021-01-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='groups',
            new_name='Group',
        ),
    ]
