# Generated by Django 3.1.5 on 2021-01-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
