# Generated by Django 3.1.5 on 2021-01-11 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20210111_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countmembers', to='social.group', unique=True),
        ),
    ]
