# Generated by Django 3.1.5 on 2021-01-11 19:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0009_auto_20210111_2112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='members',
            unique_together={('group', 'user')},
        ),
    ]
